const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });


// Load configuration from config.json
const configData = JSON.parse(fs.readFileSync('./config.json', 'utf-8'));



function convertToBool(text, fault = 'true') {
return text === fault ? true : false;
}
module.exports = {
SESSION_ID: process.env.SESSION_ID || "prince_md-eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiME1WTnRpOEIxS29nckdPeTMrTk1ic0NzWGM0OUJvQkJ3djEreHhSVElFWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQU5CeWF6bTlTRVkvLzVjcm1pZlJta0RFY0tzcXJlY1VZaFAxL2lWUnlocz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI2Q2JGdTRFN24rL3ppaXBrUmdXZFdMckhEWTE0TmhzZFRUSG5aZUhORVdVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJsMkU0NTBnVnVtc1poRXRsSUFkU0hydmR6MHhUR3h0WWN4L0hnbzc0dlJ3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im9MS0NVTW9ici8wNUI4TS80dndKSng3cG9kcTQrZFgyYmE3aUNFWWRvVkU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlpwSlY5dnU5ajh5akhMWDNlR3VYb2lITTNlb2JmN2xhcUJWdDAvbUZuRU09In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUpaa2xCd3RGcTNNSDRONy9GMkprMk5BRGVKSXJ6T2dycjFkc253NjlFYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieHpUYjBnSXBWRnBRTnJMVUZnd3g0TEUvblQ5NjJBZGNZdmR5Q1FpRm9WMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjdIOWN1Q2RpOERBMnJBYnFWNVJqQ2g3RmhwZHNnNnNwU2F3RnYxak1zSzZRUnNBS3RiRWdmSUxWMEdHdXluOTRMZzMxTDB5S0VjTGVibm93Tng4dUJRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTE3LCJhZHZTZWNyZXRLZXkiOiJ4dk1DWUNCK1hEcHRPSXE5NUpUdk1nVVBvZHE3YkVXUFhXTjZGc3FVTlhZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJ6UUVEMDRaOVI4MlZQTW1yUXNZbmFnIiwicGhvbmVJZCI6ImQ3MWQyODlhLTBiMzYtNGE0ZC1hZTc1LWJkZGYzYzJmNGMzYyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJwT1F0QlA0blFoM2RSVG8zUE5GUmNPTkhES289In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU1J2TnlQWjViWWh4bUkwdlF2RDMva2ptVUlNPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkNNNDFYWkM1IiwibWUiOnsiaWQiOiIyMzc2NzI1NzQ3Mzg6NjJAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ1BuVjN2d0NFS3YybzhBR0dDa2dBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IkU1bktQMm1uK2h2b1hGdmNVOCtaMXdoekVZenMvWFBwSDU0cnJ2aEgwdzQ9IiwiYWNjb3VudFNpZ25hdHVyZSI6IlB4cU1zZm9DY2VPZktPOU4yd0VOR01XODVNR1BoOGNqVFZ2TnpTL1h4eTU3S2lIeXl3WGhtczd6ell6cUFMN1FtcFVhVkZLb3dUVDFzYXRtTmtXMkR3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJUR1hqM3Q3VWNQUUJFUlFjU01EYjMzaHhZaWVaUGhTWW4yUC9xOFYzL01JRjVwVTA4eUhNbWwwNTJROFhMR3luWlRaNlgzVm9LNXFhbSs4cW5yZmpEUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNzY3MjU3NDczODo2MkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJST1p5ajlwcC9vYjZGeGIzRlBQbWRjSWN4R003UDF6NlIrZUs2NzRSOU1PIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzQ1NDE5MDY0LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUhKSyJ9",
AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
MODE: process.env.MODE || "public",
AUTO_VOICE: process.env.AUTO_VOICE || "false",
AUTO_STICKER: process.env.AUTO_STICKER || "false",
AUTO_REPLY: process.env.AUTO_REPLY || "false",
ALIVE_IMG: process.env.ALIVE_IMG || "https://raw.githubusercontent.com/Mayelprince/url/main/url/1264.jpg",
MENU_IMG: process.env.MENU_IMG || "https://raw.githubusercontent.com/Mayelprince/url/main/url/1264.jpg",
ALIVE_MSG: process.env.ALIVE_MSG || "Hi 💁🏽 How Can I Assist You. Am alive Now.",
ANTI_LINK: process.env.ANTI_LINK || "true",
ANTI_BAD: process.env.ANTI_BAD || "true",
PREFIX: process.env.PREFIX || ".",
ANTI_DEL_PATH: process.env.ANTI_DEL_PATH || "log",
FAKE_RECORDING: process.env.FAKE_RECORDING || "false",
FAKE_TYPING: process.env.FAKE_TYPING || "false",
ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "false",
CURRENT_STATUS: process.env.CURRENT_STATUS || "true",
AUTO_REACT: process.env.AUTO_REACT || "false",
HEART_REACT: process.env.HEART_REACT || "false",
OWNER_REACT: process.env.OWNER_REACT || "fase",
BOT_NAME: process.env.BOT_NAME || "KINDBOT",
OMDB_API_KEY: process.env.OMDB_API_KEY || "76cb7f39", // omdbapi.com
};



